# Generated by Django 2.2.3 on 2020-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='картинка'),
        ),
    ]
