# Generated by Django 2.2.3 on 2020-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20200712_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='en_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='имя на английском'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='jp_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='имя на японском'),
        ),
    ]
